# based on https://docs.gitlab.com/ce/ci/docker/using_docker_build.html
# reference: https://docs.gitlab.com/ee/ci/yaml/README.html

image: docker:latest
services:
- docker:dind

stages:
- build
# - test
- release
# - deploy

variables:
  CONTAINER_BASE_NAME:   registry.gitlab.com/joaocc/zcash-base

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:latest:
  stage: build
  script:
    - docker build --tag $CONTAINER_BASE_NAME:latest   --pull --file Dockerfile .

build:official:
  stage: build
  script:
    - docker build --tag $CONTAINER_BASE_NAME:official --pull --file Dockerfile.official .

release:latest:
  stage: release
  script:
    - docker push        $CONTAINER_BASE_NAME:latest
  only:
    - master
  dependencies:
    - build:latest

release:official:
  stage: release
  script:
    - docker push        $CONTAINER_BASE_NAME:official
  only:
    - master
  dependencies:
    - build:official

# older version (working, but only sequentially parellel)
#
# build_image:
#   image: docker:git
#   services:
#   - docker:dind
#   script:
#     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
#
#     - docker build -t registry.gitlab.com/joaocc/zcash-base --file Dockerfile           --tag latest    .
#     - docker push registry.gitlab.com/joaocc/zcash-base:latest
#
#     - docker build -t registry.gitlab.com/joaocc/zcash-base --file Dockerfile.official  --tag official  .
#     - docker push registry.gitlab.com/joaocc/zcash-base:official
#
#   only:
#     - master

