build_image:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

    - docker build -t registry.gitlab.com/joaocc/zcash-base --file Dockerfile           --tag latest    .
    - docker push registry.gitlab.com/joaocc/zcash-base:latest

    - docker build -t registry.gitlab.com/joaocc/zcash-base --file Dockerfile.original  --tag original  .
    - docker push registry.gitlab.com/joaocc/zcash-base:original

  only:
    - master
